### ISSUE TITLE
article

### ISSUE THREAD

**Issue by wsefw** [manishalingala/ICLMPC#3]
I would like to know if there are any corresponding papers that explain this code?
 Thank you very much for your sharing.

**Comment by manishalingala** [comment]
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10516585 In this paper "Sampled data based ICLMPC for TS Fuzzy systems", you can refer the algorithm and mathematical background of ICLMPC, more precisely this code is executed in example-2 of section V.

**Comment by wsefw** [comment]
Thank you very much for your prompt reply. I will read this article carefully.
